### ISSUE TITLE
Node and npm versions

### ISSUE THREAD

**Issue by xuhang57** [cyverse/troposphere-kaizen#29]
So glad this Repo is finally opened to the public! 👍 

What would be the minimum versions requirements for `NodeJS` and `npm`? 

Thanks!

**Comment by jchansen** [comment]
Hi @xuhang57. I'm not sure what the minimum would be.

I personally use Node v8 and npm v5 when working on it.

I expect Node v6 and npm v3 would also work, but haven't tried it. That guess is based in part on the fact that Webpack still runs Node v5 tests as part of their CI suite.

If you find yourself using a version of Node or npm that isn't compatible, and let us know, we can add that to the README as a known incompatibility.

I suspect that if it breaks due to a compatibility issue, it'll break during build or on page load (i.e. `npm install` or `npm start`), and not during usage of the application. So I expect it will be obvious, but I could be wrong.

**Comment by xuhang57** [comment]
Thanks @jchansen for your reply! Will let you know if I am experiencing an incompatibility.

I agree with you on it will break during the build if there is a compatibility issue. 👍
